### ISSUE TITLE
fromROSMsg() compile error

### ISSUE THREAD

**Issue by shiveshkhaitan** [ros2/cartographer_ros#21]
I am using Ubuntu 16.04 ros2 distro-bouncy compiled from source. While using colcon build for cartographer_ros I get the error
cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.cc: In function ‘cartographer::sensor::PointCloudWithIntensities cartographer_ros::ToPointCloudWithIntensities(const PointCloud2&)’:
cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.cc:178:45: error: no matching function for call to ‘fromROSMsg(const PointCloud2&, pcl::PointCloud<pcl::PointXYZI>&)’
     pcl::fromROSMsg(message, pcl_point_cloud);
                                             ^
In file included from 
cartographer_ros/cartographer_ros/./cartographer_ros/msg_conversion.h:27:0,
                 from 
cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.cc:17:
/usr/include/pcl_conversions/pcl_conversions.h:547:8: note: candidate: template<class T> void pcl::fromROSMsg(const PointCloud2&, pcl::PointCloud<PointT>&)
   void fromROSMsg(const sensor_msgs::PointCloud2 &cloud, pcl::PointCloud<T> &pcl_cloud)
        ^
/usr/include/pcl_conversions/pcl_conversions.h:547:8: note:   template argument deduction/substitution failed:
cartographer_ros/cartographer_ros/cartographer_ros/msg_conversion.cc:178:45: note:   cannot convert ‘message’ (type ‘const PointCloud2 {aka const sensor_msgs::msg::PointCloud2_<std::allocator<void> >}’) to type ‘const PointCloud2& {aka const sensor_msgs::PointCloud2_<std::allocator<void> >&}’
     pcl::fromROSMsg(message, pcl_point_cloud);

The error is reproducible in ros2 and bouncy branch

**Comment by mikaelarguedas** [comment]
Thanks @shiveshkhaitan for reporting.

The packages listed on the [turtlebot2_demo.repos](https://github.com/ros2/turtlebot2_demo/blob/bouncy/turtlebot2_demo.repos) are currently only supporting ubuntu Bionic.

The difference in system versions of `ceres` and `protobuf` between Ubuntu Xenial and Ubuntu Bionic makes maintaining a version compatible with both OSs more time consuming. I'm actually surprised you could get that far in the compilation process.


Regarding the error you are seeing, I haven;t faced it before, but it looks like you are using `pcl_conversions` from `/usr/include`. How did you install that package?

**Comment by shiveshkhaitan** [comment]
Thanks @mikaelarguedas for pointing out pcl_conversions from /usr/include. Updated pcl_conversions for ros2 but it was still using the one for ros1. Using pcl_conversions of ros2 solved the issue

**Comment by dirk-thomas** [comment]
@shiveshkhaitan If it solved your problem can you please go ahead and close the ticket.
