### ISSUE TITLE
Launch files for ros2

### ISSUE THREAD

**Issue by shiveshkhaitan** [ros2/cartographer_ros#22]
Have the launch files for ros2 not yet been updated? The launch files in cartographer_ros/launch are for ros1. How can I launch for ros2?

**Comment by sloretz** [comment]
The launch files have not been updated. See these links for more information about launch in ros2 

https://github.com/ros2/ros2/wiki/Launch-system
https://github.com/ros2/launch
https://github.com/ros2/launch/tree/master/ros2launch/examples

**Comment by mikaelarguedas** [comment]
the only launch files that have been converted to use cartographer in ROS2 are the ones available in the turtlebot2_demo repository: https://github.com/ros2/turtlebot2_demo/tree/master/turtlebot2_cartographer/launch.

**Comment by shiveshkhaitan** [comment]
Thank you for the information @mikaelarguedas  @sloretz
