### ISSUE TITLE
Proper QoS profiles for sensor messages

### ISSUE THREAD

**Issue by bigdayangyu** [ros2/cartographer_ros#28]
The current cartographer_ros node.cc uses ` rmw_qos_profile_default` as QoS profile for all sensor messages. It might be more appropriate to use `rmw_qos_profile_sensor_data` profile. 
@Karsten1987
https://github.com/ros2/cartographer_ros/blob/d4c62f7bf43dba1c4db582b47aa017b6fd7633b1/cartographer_ros/cartographer_ros/node.cc#L444-L475

**Comment by clalancette** [comment]
Yes, that may be the case.  When I did the initial port, I was having some trouble with that, but that was probably an error on my part.  I'd welcome a pull request that did that, but I'd want to see some results from testing before we merged.

**Comment by clalancette** [comment]
This was actually done in #29, so I'm going to close this out.  Feel free to reopen if this doesn't work for you.  Thanks.
