### ISSUE TITLE
Will this package be released binary?

### ISSUE THREAD

**Issue by routiful** [ros2/cartographer_ros#33]
I found that `cartographer` package could be installed via apt command.
But this package couldn't be.

Do you have a plan to released this to binary?

**Comment by robotpilot** [comment]
Hi @clalancette 
We are preparing to provide the binary packages for TurtleBot3 on ROS 2 Dashing Diademata.
https://github.com/ROBOTIS-GIT/turtlebot3/issues/460
The [TurtleBot3 packages](https://github.com/ROBOTIS-GIT/turtlebot3/tree/ros2) depend on `cartographer_ros`, so the `cartographer_ros` package must be released first. We need your support. :)

**Comment by clalancette** [comment]
@robotpilot Sorry for being quiet here.  I will do a release of this package into Dashing, but it may not be until next week.

**Comment by robotpilot** [comment]
@clalancette Good! Thank you for your support. :)

**Comment by robotpilot** [comment]
@clalancette If you go up to build farm, send a ping to me. I will also register the turtlebot3 package.

**Comment by clalancette** [comment]
All right, I've now released and merged https://github.com/ros/rosdistro/pull/22142 into Dashing.  I'll close this out; thanks for the patience.

**Comment by robotpilot** [comment]
@clalancette, 
Wow! Very good news. We will test this and proceed with the relevant release. 
Thank you very much.
