### ISSUE TITLE
Are there cartographer_rviz and cartographer_occupancy_grid_node here?

### ISSUE THREAD

**Issue by chargerKong** [ros2/cartographer_ros#52]
I have cloned the cartographer and cartographer_ros in src file folder
But I can not find the cartographer_rviz when i colcon build the packages
and it can not find the cartographer_occupancy_grid_node in  cartographer_ros

Are there cartographer_rviz and cartographer_occupancy_grid_node here?

**Comment by clalancette** [comment]
The `occupancy_grid_node` should be available; what branch did you build?

We never ported `cartographer_rviz` to ROS 2, so that is not available.

**Comment by chargerKong** [comment]
Thanks! `occupancy_grid_node` does work.
And I see the issue [https://github.com/ros2/cartographer_ros/issues/32](url)
