### ISSUE TITLE
How to convert pbstream to a ros map?

### ISSUE THREAD

**Issue by chargerKong** [ros2/cartographer_ros#53]
In ROS1，we could save ros map through
```
rosrun cartographer_ros cartographer_pbstream_to_ros_map -pbstream_filename=xxx.pbstream  -map_filestem=xxx
```
I did not find `cartographer_pbstream_to_ros_map` here

How to save ros map in ROS2?

Thanks in advance

**Comment by clalancette** [comment]
In short, we never ported "cartographer_pbstream_to_ros_map" to ROS 2.  That said, it doesn't seem to use much ROS functionality, so it might be a trivial port.  If you port it and open a pull request, I'm happy to review it.

**Comment by chargerKong** [comment]
@clalancette I've made a pull request. Please have a look, thanks
