### ISSUE TITLE
"rosbag2_cpp" and "urdf" packages can't be found in rolling CI server（ros2 branch）

### ISSUE THREAD

**Issue by chargerKong** [ros2/cartographer_ros#58]
Recently, I've ported the assets_writer to ROS2, #57 
But rolling CI server（ros2 branch）shows it can't find the `rosbag2_cpp` and `urdf`  packages

I think it should be installed into the rolling CI server

**Comment by clalancette** [comment]
The issue is that you need to declare `rosbag2_cpp` and `urdf` as dependencies in the package.xml in that PR, otherwise the server will never install them.  I'll put a similar comment in that PR.
