### ISSUE TITLE
Version selection of compiling cartographer-ros and cartographer on ros-foxy

### ISSUE THREAD

**Issue by the-sword** [ros2/cartographer_ros#62]
If I want to compile cartographer on ros2-foxy version, which tag of cartographer and cartographer-ros should I choose?

ubuntu 20.04 
ros2-foxy

Thanks a lot if anyone can help

**Comment by clalancette** [comment]
If you don't want to build it, you should be able to just `apt-get install ros-foxy-cartographer-ros`.

If you do want to build it, then you need cartographer_ros branch `dashing` and cartographer branch `foxy` (it's a little confusing, sorry about that).

**Comment by MaZhengg** [comment]
Is there any change for the branch `dashing` we should choose on OS(ubuntu 20.04 and ros2-foxy) now? 
cause there is no python type launch file in the `dasing` branch
Thanks a lot for your help
